{% set name = "written" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/written-{{ version }}.tar.gz
  sha256: 4940777e7bcee20b8cb1ff006fda8d216f5b88bdecc3b37d85f6065f8b5522f5

build:
  entry_points:
    - written = written.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.5

test:
  imports:
    - written
  commands:
    - pip check
    - written --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/written
  summary: Try to atomically write data to a file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
